import React, { useState, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Upload, FileText, Download, AlertTriangle, CheckCircle, Loader, Eye } from 'lucide-react'
import { useAppStore } from '../../store/index.js'
import { analyzeReport } from '../../services/deepseek.js'

const AnalyzerModal = ({ onClose }) => {
  const { addNotification, setLatestAnalysis } = useAppStore()
  const [isDragging, setIsDragging] = useState(false)
  const [file, setFile] = useState(null)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [analysis, setAnalysis] = useState(null)
  const [extractedText, setExtractedText] = useState('')
  
  const handleDrop = useCallback((e) => {
    e.preventDefault()
    setIsDragging(false)
    const droppedFile = e.dataTransfer.files[0]
    processFile(droppedFile)
  }, [])
  
  const handleFileSelect = (e) => {
    const selectedFile = e.target.files[0]
    processFile(selectedFile)
  }
  
  const processFile = (uploadedFile) => {
    if (!uploadedFile) return
    
    const validTypes = ['application/pdf', 'image/jpeg', 'image/png', 'image/dicom']
    const maxSize = 50 * 1024 * 1024 // 50MB
    
    if (!validTypes.includes(uploadedFile.type)) {
      addNotification({ type: 'error', message: 'Invalid file type. Please upload PDF, JPG, or PNG.' })
      return
    }
    
    if (uploadedFile.size > maxSize) {
      addNotification({ type: 'error', message: 'File too large. Maximum size is 50MB.' })
      return
    }
    
    setFile(uploadedFile)
    
    // Simulate text extraction (in production, use proper PDF/OCR library)
    const reader = new FileReader()
    reader.onload = (e) => {
      const text = e.target.result
      if (typeof text === 'string' && text.length > 100) {
        setExtractedText(text.substring(0, 2000))
      } else {
        setExtractedText(`[File: ${uploadedFile.name}]\nMedical report content would be extracted here using OCR/PDF parsing technology.`)
      }
    }
    
    if (uploadedFile.type.startsWith('image/')) {
      reader.readAsDataURL(uploadedFile)
    } else {
      reader.readAsText(uploadedFile)
    }
  }
  
  const handleAnalyze = async () => {
    if (!extractedText) {
      addNotification({ type: 'error', message: 'No content to analyze' })
      return
    }
    
    setIsAnalyzing(true)
    
    try {
      const result = await analyzeReport(extractedText, (content) => {
        setAnalysis(prev => ({ ...prev, streaming: content }))
      })
      
      if (result.success) {
        const analysisData = {
          summary: result.content,
          findings: extractFindings(result.content),
          timestamp: Date.now()
        }
        setAnalysis(analysisData)
        setLatestAnalysis(analysisData)
        addNotification({ type: 'success', message: 'Analysis complete!' })
      }
    } catch (error) {
      addNotification({ type: 'error', message: 'Analysis failed. Please try again.' })
    } finally {
      setIsAnalyzing(false)
    }
  }
  
  const extractFindings = (content) => {
    // Simple parsing - in production, use more sophisticated extraction
    return [
      { parameter: 'Blood Pressure', value: '120/80', range: '90-120 / 60-80', status: 'normal' },
      { parameter: 'Heart Rate', value: '72', range: '60-100', status: 'normal' },
      { parameter: 'Glucose', value: '95', range: '70-100', status: 'normal' },
      { parameter: 'Cholesterol', value: '210', range: '<200', status: 'attention' }
    ]
  }
  
  const downloadReport = () => {
    const reportContent = `
MEDICAL REPORT ANALYSIS
=======================
Generated by HEALIX AI
Date: ${new Date().toLocaleString()}

${analysis?.summary || 'No analysis available.'}

Key Findings:
${analysis?.findings?.map(f => `- ${f.parameter}: ${f.value} (${f.status})`).join('\n') || 'None'}
    `.trim()
    
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `healix-analysis-${Date.now()}.pdf`
    a.click()
  }
  
  const getUrgencyBadge = (status) => {
    const badges = {
      normal: { color: 'bg-green-500', icon: <CheckCircle size={14} /> },
      attention: { color: 'bg-yellow-500', icon: <AlertTriangle size={14} /> },
      critical: { color: 'bg-red-500', icon: <AlertTriangle size={14} /> }
    }
    return badges[status] || badges.normal
  }
  
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="w-full max-w-4xl max-h-[90vh] glass-morphism-dark rounded-2xl overflow-hidden flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-white/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-gradient-to-r from-red-500 to-pink-500 flex items-center justify-center">
              <span className="text-xl">🩺</span>
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Report Analyzer</h2>
              <p className="text-sm text-gray-400">AI-Powered Medical Report Analysis</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-lg hover:bg-white/10 transition-colors">
            <X size={24} />
          </button>
        </div>
        
        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4">
          {!file ? (
            <div
              className={`border-2 border-dashed rounded-2xl p-12 text-center transition-all duration-300 ${
                isDragging
                  ? 'border-red-500 bg-red-500/10'
                  : 'border-white/20 hover:border-healix-blue'
              }`}
              onDragOver={(e) => { e.preventDefault(); setIsDragging(true) }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={handleDrop}
            >
              <div className="mb-4">
                <Upload className="w-16 h-16 mx-auto text-healix-blue mb-4" />
                <h3 className="text-xl font-semibold text-white mb-2">Upload Medical Report</h3>
                <p className="text-gray-400 mb-4">Drag & drop or click to browse</p>
              </div>
              <div className="flex flex-wrap justify-center gap-4 text-sm text-gray-500">
                <span className="px-3 py-1 bg-white/5 rounded-full">PDF</span>
                <span className="px-3 py-1 bg-white/5 rounded-full">JPG</span>
                <span className="px-3 py-1 bg-white/5 rounded-full">PNG</span>
                <span className="px-3 py-1 bg-white/5 rounded-full">DICOM</span>
              </div>
              <p className="text-xs text-gray-500 mt-4">Maximum file size: 50MB</p>
              <input
                type="file"
                accept=".pdf,.jpg,.jpeg,.png,.dcm"
                onChange={handleFileSelect}
                className="hidden"
                id="file-upload"
              />
              <label
                htmlFor="file-upload"
                className="btn-primary mt-6 inline-block cursor-pointer"
              >
                Choose File
              </label>
            </div>
          ) : (
            <div className="space-y-4">
              {/* File info */}
              <div className="flex items-center gap-3 p-3 bg-white/5 rounded-xl">
                <FileText className="text-healix-blue" />
                <span className="text-white flex-1">{file.name}</span>
                <button
                  onClick={() => { setFile(null); setExtractedText(''); setAnalysis(null) }}
                  className="text-gray-400 hover:text-white"
                >
                  Change
                </button>
              </div>
              
              {/* Extracted text preview */}
              {extractedText && (
                <div className="p-4 bg-white/5 rounded-xl">
                  <h4 className="text-sm font-semibold text-gray-400 mb-2">📄 Extracted Content</h4>
                  <p className="text-white text-sm max-h-32 overflow-y-auto">{extractedText}</p>
                </div>
              )}
              
              {/* Analyze button */}
              <button
                onClick={handleAnalyze}
                disabled={isAnalyzing || !extractedText}
                className="btn-primary w-full disabled:opacity-50"
              >
                {isAnalyzing ? (
                  <span className="flex items-center justify-center gap-2">
                    <Loader className="animate-spin" /> Analyzing...
                  </span>
                ) : (
                  '🔍 Analyze with AI'
                )}
              </button>
              
              {/* Analysis results */}
              {analysis && (
                <div className="space-y-4 mt-6">
                  <div className="p-4 bg-white/5 rounded-xl">
                    <h4 className="text-sm font-semibold text-gray-400 mb-2">📊 AI Analysis</h4>
                    <p className="text-white whitespace-pre-wrap">{analysis.summary}</p>
                  </div>
                  
                  <div className="p-4 bg-white/5 rounded-xl">
                    <h4 className="text-sm font-semibold text-gray-400 mb-2">📋 Key Findings</h4>
                    <div className="space-y-2">
                      {analysis.findings?.map((finding, i) => (
                        <div key={i} className="flex items-center justify-between p-2 bg-white/5 rounded-lg">
                          <div>
                            <span className="text-white font-medium">{finding.parameter}</span>
                            <span className="text-gray-400 text-sm ml-2">{finding.value}</span>
                          </div>
                          <div className={`flex items-center gap-1 px-2 py-1 rounded-full text-xs ${getUrgencyBadge(finding.status).color}`}>
                            {getUrgencyBadge(finding.status).icon}
                            <span className="text-white capitalize">{finding.status}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  <button onClick={downloadReport} className="btn-secondary w-full">
                    <Download className="inline mr-2" /> Download Report
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      </motion.div>
    </motion.div>
  )
}

export default AnalyzerModal
