apiVersion: v1
kind: Namespace
metadata:
  name: healix
  labels:
    name: healix
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - healix-deployment.yaml
  - healix-service.yaml
  - healix-ingress.yaml
  - healix-configmap.yaml
  - healix-secret.yaml

images:
  - name: healix
    newTag: latest

commonLabels:
  app: healix
  environment: production